### ISSUE TITLE
Any timeline for release?

### ISSUE THREAD

**Issue by cvkmohan** [BeaconCMS/page_builder#9]
Hello, 
Came to this page after watching https://www.youtube.com/watch?v=5jk0fIJOFuc video at Elixir Conf on Beacon. The complete integration between page builder and code editor in the video looked awesome. 
My question: Is the page builder in development? Will it be open sourced? If yes, any timelines?

PS: Sorry, this is not an issue. But as the discussions tab is not enabled, I had to create as an issue.

**Comment by leandrocp** [comment]
Hi @cvkmohan,

@cibernox is actively working to integrate the code in this repo into Beacon LiveAdmin, see https://github.com/BeaconCMS/beacon_live_admin/pull/80

Yes, it will be open source and should be released in the next few days but keep in mind that should be considered a pre-release version.

Thanks for watching the talk and the interest in the project, I'm closing this issue for now but feel free to post more comments or open more issues.
